### ISSUE TITLE
hidapi.dll not found

### ISSUE THREAD

**Issue by spiralingtides** [dheygere/k780-fn-lock-for-windows#1]
Hey, thanks for sharing your solution. 

I unpacked the precompiled binary and ran "setFnKeys.exe" but got the error "The code execution cannot proceed because hidapi.dll was not found. Reinstalling the program may fix this problem." 

Where is the correct place to get this file and which folder should it be in? Thanks I'm advanced.

**Comment by spiralingtides** [comment]
This one? https://github.com/libusb/hidapi

**Comment by dheygere** [comment]
Oops, I forgot to include the dll in the zip. 
The dll comes from https://github.com/libusb/hidapi indeed.
But for convenience you can download hidapi.dll from this repo, here :
https://github.com/dheygere/k780-fn-lock-for-windows/blob/main/hidapi/x86/hidapi.dll
Place the downloaded dll in the same folder as "setFnKeys.exe".

**Comment by spiralingtides** [comment]
Awesome! Thanks so much!
